# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: infer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'infer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0binfer.proto\x12\tstreamcat\"4\n\x06Tensor\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x03\x12\r\n\x05\x64type\x18\x03 \x01(\t\"Z\n\x0cInferRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12 \n\x05input\x18\x02 \x01(\x0b\x32\x11.streamcat.Tensor\x12\x14\n\x0ctimestamp_ns\x18\x03 \x01(\x03\"P\n\nInferReply\x12!\n\x06output\x18\x01 \x01(\x0b\x32\x11.streamcat.Tensor\x12\x10\n\x08infer_ms\x18\x02 \x01(\x01\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"\x0f\n\rHealthRequest\";\n\x0bHealthReply\x12\x0c\n\x04live\x18\x01 \x01(\x08\x12\r\n\x05ready\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2\x87\x01\n\x10InferenceService\x12\x37\n\x05Infer\x12\x17.streamcat.InferRequest\x1a\x15.streamcat.InferReply\x12:\n\x06Health\x12\x18.streamcat.HealthRequest\x1a\x16.streamcat.HealthReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSOR']._serialized_start=26
  _globals['_TENSOR']._serialized_end=78
  _globals['_INFERREQUEST']._serialized_start=80
  _globals['_INFERREQUEST']._serialized_end=170
  _globals['_INFERREPLY']._serialized_start=172
  _globals['_INFERREPLY']._serialized_end=252
  _globals['_HEALTHREQUEST']._serialized_start=254
  _globals['_HEALTHREQUEST']._serialized_end=269
  _globals['_HEALTHREPLY']._serialized_start=271
  _globals['_HEALTHREPLY']._serialized_end=330
  _globals['_INFERENCESERVICE']._serialized_start=333
  _globals['_INFERENCESERVICE']._serialized_end=468
# @@protoc_insertion_point(module_scope)
